### PR TITLE
Add Event and Membership classes and extract classes into their own files

### PR DESCRIPTION
**Pull request by henare**
This continues on from #16 to cover some more Popolo classes.

It also extracts most classes and tests into their own files as the single files were getting rather large. This is a first step to #13.

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Thanks @henare (and @equivalentideas)

This all looks great (with the same caveat as before that it would be really good to clean up a lot of that duplication real soon). The only other thing I'd like to see here before merging is for `README.md` to be brought up to date. Ideally it would show a few more examples, but at a minimum it shouldn't claim "Currently only the `persons` and `organizations` collections are implemented" :)

My suspicion is that the 'ensure start_date / end_date are always present' will end up being factored away into class data or something too, rather than needing to explicitly define the methods, but no need to do that until we've seen what exactly the pattern is.

**Comment by henare** [comment]
> This all looks great (with the same caveat as before that it would be really good to clean up a lot of that duplication real soon).

:+1: 

> The only other thing I'd like to see here before merging is for README.md to be brought up to date. Ideally it would show a few more examples, but at a minimum it shouldn't claim "Currently only the persons and organizations collections are implemented" :)

We've just updated the README so far (we're happy to add the examples too but it's late on a Friday now).

As I said in the README I think we now cover all Popolo classes used by EveryPolitician. This brings me to a question we have. In publicwhip we use `vote_event` and `vote`, would you like a pull request to add them to this Gem as well or is that out of scope because votes aren't part of EveryPolitician?

> My suspicion is that the 'ensure start_date / end_date are always present' will end up being factored away into class data or something too, rather than needing to explicitly define the methods, but no need to do that until we've seen what exactly the pattern is. 

:+1:

**Comment by tmtmtmtm** [comment]
Looks great! :rocket: 

> We've just updated the README so far (we're happy to add the examples too but it's late on 
> a Friday now

No worries — this is good like this. I suspect we'll be adding more functionality to this very soon, so we'll look into extending the docs then.

> In publicwhip we use vote_event and vote, would you like a pull request to add them 
> to this Gem as well or is that out of scope because votes aren't part of EveryPolitician?

Hmmm. Need to think about that one a bit.

We probably _will_ be adding Votes to EveryPolitician fairly soon, but I strongly suspect our preference will be to have those in a separate JSON file. Ideally the library would be able to seamlessly handle setups like that though, and merrily handle all the 'joins' so you can still ask for `person.votes` etc.

I'm a little worried about adding it until we have use for it in at least two countries though, so that we don't bake assumptions in too deeply — it's always harder to change the interface of a publicly facing library than something that's purely internal. 

If we were to hold off on this for now, would you be essentially working off your own fork that also handled votes, or would you deal with those a different way?

**Comment by henare** [comment]
Thanks for the review and merge :sunny: 

> ...and merrily handle all the 'joins' so you can still ask for person.votes etc.

Great minds... we're going to look at adding specific bits of this for our People loader next :smile: 

> If we were to hold off on this for now, would you be essentially working off your own fork that also handled votes, or would you deal with those a different way?

I think we'd just keep using the raw Popolo for votes but via this Gem :ok_hand:

**Comment by chrismytton** [comment]
@henare @equivalentideas This is awesome, thanks for taking the time to do this! :sparkles: 

I've just pushed v0.2.0 to RubyGems which contains these changes.

**Pull request merged**
